# Generated by Django 2.1.5 on 2020-03-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choonz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='linkToSpotify',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='numberOfPlaylists',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='webpage',
        ),
    ]
