# Generated by Django 2.1.5 on 2020-03-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choonz', '0002_auto_20200308_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='linkOther',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='linkToSpotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
