# Generated by Django 2.1.5 on 2020-03-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choonz', '0004_song_numberofplaylists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
